"""empty message

Revision ID: 21d3da26ff60
Revises: 3b9b66f5d334
Create Date: 2015-06-06 15:05:00.507362

"""

# revision identifiers, used by Alembic.
revision = '21d3da26ff60'
down_revision = '3b9b66f5d334'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
