"""empty message

Revision ID: 2c2612514fca
Revises: 35ecb57cde54
Create Date: 2015-06-16 23:24:52.223504

"""

# revision identifiers, used by Alembic.
revision = '2c2612514fca'
down_revision = '35ecb57cde54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'web_users_pkey'),
    sa.UniqueConstraint('username', name=u'web_users_username_key')
    )
    ### end Alembic commands ###
