"""empty message

Revision ID: 326004e30f61
Revises: None
Create Date: 2015-06-06 15:03:37.941844

"""

# revision identifiers, used by Alembic.
revision = '326004e30f61'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    ### end Alembic commands ###
