"""empty message

Revision ID: 35ecb57cde54
Revises: 4cbc815993a4
Create Date: 2015-06-13 00:14:48.848853

"""

# revision identifiers, used by Alembic.
revision = '35ecb57cde54'
down_revision = '4cbc815993a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
