"""empty message

Revision ID: 3b9b66f5d334
Revises: 326004e30f61
Create Date: 2015-06-06 15:04:10.630413

"""

# revision identifiers, used by Alembic.
revision = '3b9b66f5d334'
down_revision = '326004e30f61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
