"""empty message

Revision ID: 4cbc815993a4
Revises: 21d3da26ff60
Create Date: 2015-06-13 00:13:51.552704

"""

# revision identifiers, used by Alembic.
revision = '4cbc815993a4'
down_revision = '21d3da26ff60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('favorite', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'favorite')
    ### end Alembic commands ###
