"""empty message

Revision ID: ff38688c172
Revises: None
Create Date: 2015-06-19 11:12:53.544984

"""

# revision identifiers, used by Alembic.
revision = 'ff38688c172'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
